// Comprehensive Product Data for Asper Beauty Shop
// Curated selection of premium beauty products available in Jordan

export interface ProductData {
  id: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  category: string;
  subcategory: string;
  brand: string;
  price: number;
  originalPrice?: number;
  discountPercent?: number;
  isOnSale: boolean;
  volumeMl?: string;
  imageUrl?: string;
  skinConcerns: string[];
  tags: string[];
  sku: string;
  inStock: boolean;
}

// Generate a unique ID
const generateId = () => Math.random().toString(36).substring(2, 15);

// Comprehensive product catalog
export const PRODUCT_CATALOG: ProductData[] = [
  // ==================== SKIN CARE ====================
  // Vichy Products
  {
    id: generateId(),
    title: "Vichy Mineral 89 Hyaluronic Acid Serum",
    titleAr: "فيشي مينرال 89 سيروم حمض الهيالورونيك",
    description: "Fortifying and hydrating daily booster with 89% mineralizing thermal water and hyaluronic acid. Strengthens skin and restores glow.",
    descriptionAr: "معزز يومي للترطيب والتقوية مع 89% من المياه الحرارية المعدنية وحمض الهيالورونيك. يقوي البشرة ويستعيد التوهج.",
    category: "Skin Care",
    subcategory: "serums",
    brand: "Vichy",
    price: 45.00,
    originalPrice: 52.00,
    discountPercent: 13,
    isOnSale: true,
    volumeMl: "50ml",
    skinConcerns: ["hydration", "anti-aging", "sensitivity"],
    tags: ["bestseller", "dermatologist-recommended"],
    sku: "VIC-MIN89-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Vichy Normaderm Phytosolution Daily Care",
    titleAr: "فيشي نورماديرم فيتوسوليوشن العناية اليومية",
    description: "Double-action moisturizer that targets imperfections and signs of aging. Oil-free formula with salicylic acid.",
    descriptionAr: "مرطب مزدوج الفعالية يستهدف الشوائب وعلامات الشيخوخة. تركيبة خالية من الزيوت مع حمض الساليسيليك.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Vichy",
    price: 38.50,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: ["acne", "oily-skin"],
    tags: ["oil-free", "acne-prone"],
    sku: "VIC-NORM-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Vichy Liftactiv Supreme Anti-Wrinkle Cream",
    titleAr: "فيشي ليفت أكتيف سوبريم كريم مضاد للتجاعيد",
    description: "Progressive anti-wrinkle and firming care that lifts and firms for visible transformation.",
    descriptionAr: "عناية تدريجية مضادة للتجاعيد ومشدة ترفع وتشد للحصول على تحول مرئي.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Vichy",
    price: 55.00,
    originalPrice: 62.00,
    discountPercent: 11,
    isOnSale: true,
    volumeMl: "50ml",
    skinConcerns: ["anti-aging", "wrinkles"],
    tags: ["anti-aging", "lifting"],
    sku: "VIC-LIFT-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Vichy Purete Thermale 3-in-1 Micellar Water",
    titleAr: "فيشي بيوريتيه تيرمال ماء ميسيلار 3 في 1",
    description: "Gentle micellar water that cleanses, removes makeup and soothes skin in one step. Suitable for sensitive skin.",
    descriptionAr: "ماء ميسيلار لطيف ينظف ويزيل المكياج ويهدئ البشرة في خطوة واحدة. مناسب للبشرة الحساسة.",
    category: "Skin Care",
    subcategory: "cleansers",
    brand: "Vichy",
    price: 28.00,
    isOnSale: false,
    volumeMl: "400ml",
    skinConcerns: ["sensitivity", "cleansing"],
    tags: ["gentle", "micellar"],
    sku: "VIC-MIC-400",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Vichy Capital Soleil UV-Age Daily SPF50+",
    titleAr: "فيشي كابيتال سوليل يو في ايج ديلي SPF50+",
    description: "Anti-ageing sun protection that protects against UVA, UVB and infrared rays while targeting signs of aging.",
    descriptionAr: "حماية شمسية مضادة للشيخوخة تحمي من أشعة UVA و UVB والأشعة تحت الحمراء مع استهداف علامات الشيخوخة.",
    category: "Skin Care",
    subcategory: "sun-protection",
    brand: "Vichy",
    price: 42.00,
    isOnSale: false,
    volumeMl: "40ml",
    skinConcerns: ["sun-protection", "anti-aging"],
    tags: ["SPF50", "anti-aging"],
    sku: "VIC-SOL-40",
    inStock: true,
  },

  // Eucerin Products
  {
    id: generateId(),
    title: "Eucerin DermoPurifyer Oil Control Mattifying Fluid",
    titleAr: "يوسرين ديرمو بيوريفاير فلويد للتحكم بالزيوت",
    description: "8-hour mattifying fluid with Licochalcone A that reduces shine and sebum production.",
    descriptionAr: "فلويد مطفي لمدة 8 ساعات مع ليكوكالكون أ يقلل اللمعان وإنتاج الدهون.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Eucerin",
    price: 32.00,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: ["oily-skin", "acne"],
    tags: ["oil-control", "mattifying"],
    sku: "EUC-MATT-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Eucerin Hyaluron-Filler Day Cream SPF15",
    titleAr: "يوسرين هيالورون فيلر كريم نهاري SPF15",
    description: "Anti-wrinkle day cream that plumps up deep wrinkles from within and protects from UV rays.",
    descriptionAr: "كريم نهاري مضاد للتجاعيد يملأ التجاعيد العميقة من الداخل ويحمي من الأشعة فوق البنفسجية.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Eucerin",
    price: 48.00,
    originalPrice: 55.00,
    discountPercent: 13,
    isOnSale: true,
    volumeMl: "50ml",
    skinConcerns: ["anti-aging", "wrinkles", "hydration"],
    tags: ["anti-wrinkle", "hyaluronic"],
    sku: "EUC-HYA-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Eucerin AQUAporin ACTIVE Moisturizing Cream",
    titleAr: "يوسرين أكوابورين أكتيف كريم مرطب",
    description: "Intensive long-lasting hydration that supports skin's own moisture distribution system.",
    descriptionAr: "ترطيب مكثف طويل الأمد يدعم نظام توزيع الرطوبة الخاص بالبشرة.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Eucerin",
    price: 35.00,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: ["hydration", "dry-skin"],
    tags: ["intense-hydration", "all-skin-types"],
    sku: "EUC-AQU-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Eucerin Anti-Pigment Day Cream SPF30",
    titleAr: "يوسرين أنتي بيجمنت كريم نهاري SPF30",
    description: "Reduces dark spots and prevents their reappearance for an even, radiant complexion.",
    descriptionAr: "يقلل البقع الداكنة ويمنع ظهورها مجدداً للحصول على بشرة موحدة ومشرقة.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Eucerin",
    price: 52.00,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: ["dark-spots", "sun-protection"],
    tags: ["anti-pigmentation", "SPF30"],
    sku: "EUC-PIG-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Eucerin Sun Sensitive Protect Fluid SPF50+",
    titleAr: "يوسرين صن فلويد للبشرة الحساسة SPF50+",
    description: "Ultra-light sun protection for face that is non-comedogenic and leaves no white residue.",
    descriptionAr: "حماية شمسية خفيفة جداً للوجه لا تسد المسام ولا تترك آثار بيضاء.",
    category: "Skin Care",
    subcategory: "sun-protection",
    brand: "Eucerin",
    price: 36.00,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: ["sun-protection", "sensitivity"],
    tags: ["SPF50", "lightweight"],
    sku: "EUC-SUN-50",
    inStock: true,
  },

  // Bioderma Products
  {
    id: generateId(),
    title: "Bioderma Sensibio H2O Micellar Water",
    titleAr: "بيوديرما سنسيبيو H2O ماء ميسيلار",
    description: "The original micellar water for sensitive skin. Gently cleanses and removes makeup without rinsing.",
    descriptionAr: "ماء الميسيلار الأصلي للبشرة الحساسة. ينظف ويزيل المكياج بلطف دون شطف.",
    category: "Skin Care",
    subcategory: "cleansers",
    brand: "Bioderma",
    price: 25.00,
    isOnSale: false,
    volumeMl: "500ml",
    skinConcerns: ["sensitivity", "cleansing"],
    tags: ["bestseller", "gentle"],
    sku: "BIO-SEN-500",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Bioderma Sebium H2O Micellar Water",
    titleAr: "بيوديرما سيبيوم H2O ماء ميسيلار",
    description: "Purifying micellar water for oily to combination skin. Removes makeup and excess sebum.",
    descriptionAr: "ماء ميسيلار منقي للبشرة الدهنية إلى المختلطة. يزيل المكياج والدهون الزائدة.",
    category: "Skin Care",
    subcategory: "cleansers",
    brand: "Bioderma",
    price: 25.00,
    isOnSale: false,
    volumeMl: "500ml",
    skinConcerns: ["oily-skin", "cleansing"],
    tags: ["oil-control", "purifying"],
    sku: "BIO-SEB-500",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Bioderma Photoderm MAX Cream SPF50+",
    titleAr: "بيوديرما فوتوديرم ماكس كريم SPF50+",
    description: "Very high sun protection for sensitive skin with Cellular Bioprotection.",
    descriptionAr: "حماية شمسية عالية جداً للبشرة الحساسة مع حماية خلوية حيوية.",
    category: "Skin Care",
    subcategory: "sun-protection",
    brand: "Bioderma",
    price: 35.00,
    isOnSale: false,
    volumeMl: "40ml",
    skinConcerns: ["sun-protection", "sensitivity"],
    tags: ["SPF50", "high-protection"],
    sku: "BIO-PHO-40",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Bioderma Atoderm Intensive Baume",
    titleAr: "بيوديرما أتوديرم بلسم مكثف",
    description: "Ultra-soothing balm for very dry to atopic skin. Restores barrier and relieves itching.",
    descriptionAr: "بلسم مهدئ للغاية للبشرة الجافة جداً إلى الأتوبية. يستعيد الحاجز ويخفف الحكة.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Bioderma",
    price: 32.00,
    isOnSale: false,
    volumeMl: "500ml",
    skinConcerns: ["dry-skin", "sensitivity"],
    tags: ["intensive-care", "atopic"],
    sku: "BIO-ATO-500",
    inStock: true,
  },

  // Cetaphil Products
  {
    id: generateId(),
    title: "Cetaphil Gentle Skin Cleanser",
    titleAr: "سيتافيل منظف لطيف للبشرة",
    description: "Mild, non-irritating cleanser for all skin types including sensitive skin.",
    descriptionAr: "منظف لطيف غير مهيج لجميع أنواع البشرة بما في ذلك البشرة الحساسة.",
    category: "Skin Care",
    subcategory: "cleansers",
    brand: "Cetaphil",
    price: 18.00,
    isOnSale: false,
    volumeMl: "500ml",
    skinConcerns: ["sensitivity", "cleansing"],
    tags: ["gentle", "dermatologist-recommended"],
    sku: "CET-GEN-500",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Cetaphil Moisturizing Lotion",
    titleAr: "سيتافيل لوشن مرطب",
    description: "Lightweight, non-greasy moisturizer that provides immediate and long-lasting hydration.",
    descriptionAr: "مرطب خفيف غير دهني يوفر ترطيبًا فوريًا وطويل الأمد.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Cetaphil",
    price: 22.00,
    isOnSale: false,
    volumeMl: "500ml",
    skinConcerns: ["hydration", "dry-skin"],
    tags: ["lightweight", "daily-use"],
    sku: "CET-MOI-500",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Cetaphil PRO Oil Absorbing Moisturizer SPF30",
    titleAr: "سيتافيل برو مرطب ماص للزيوت SPF30",
    description: "Oil-free moisturizer with SPF that absorbs oil and provides 8-hour mattifying effect.",
    descriptionAr: "مرطب خالي من الزيوت مع حماية شمسية يمتص الزيوت ويوفر تأثير مطفي لمدة 8 ساعات.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "Cetaphil",
    price: 28.00,
    isOnSale: false,
    volumeMl: "118ml",
    skinConcerns: ["oily-skin", "sun-protection"],
    tags: ["oil-control", "SPF30"],
    sku: "CET-PRO-118",
    inStock: true,
  },

  // SVR Products
  {
    id: generateId(),
    title: "SVR Sebiaclear Serum",
    titleAr: "إس في أر سيبياكلير سيروم",
    description: "Anti-blemish and anti-marks serum with gluconolactone and niacinamide.",
    descriptionAr: "سيروم مضاد للشوائب والعلامات مع جلوكونولاكتون ونياسيناميد.",
    category: "Skin Care",
    subcategory: "serums",
    brand: "SVR",
    price: 38.00,
    originalPrice: 45.00,
    discountPercent: 16,
    isOnSale: true,
    volumeMl: "30ml",
    skinConcerns: ["acne", "dark-spots"],
    tags: ["anti-blemish", "niacinamide"],
    sku: "SVR-SEB-30",
    inStock: true,
  },
  {
    id: generateId(),
    title: "SVR Hydracid C20 Cream",
    titleAr: "إس في أر هيدراسيد C20 كريم",
    description: "Anti-oxidant and radiance cream with 20% vitamin C derivative.",
    descriptionAr: "كريم مضاد للأكسدة ومشرق مع 20% مشتق فيتامين سي.",
    category: "Skin Care",
    subcategory: "moisturizers",
    brand: "SVR",
    price: 42.00,
    isOnSale: false,
    volumeMl: "30ml",
    skinConcerns: ["dark-spots", "anti-aging"],
    tags: ["vitamin-c", "brightening"],
    sku: "SVR-HYD-30",
    inStock: true,
  },

  // ==================== HAIR CARE ====================
  // Palmer's Hair Products
  {
    id: generateId(),
    title: "Palmer's Olive Oil Formula Conditioning Spray Oil",
    titleAr: "بالمرز بخاخ زيت الزيتون المكيف",
    description: "Extra virgin olive oil shine therapy spray that adds brilliant shine to dry, dull hair.",
    descriptionAr: "بخاخ علاجي للمعان بزيت الزيتون البكر الممتاز يضيف لمعانًا للشعر الجاف والباهت.",
    category: "Hair Care",
    subcategory: "treatments",
    brand: "Palmer's",
    price: 8.50,
    isOnSale: false,
    volumeMl: "178ml",
    skinConcerns: [],
    tags: ["shine", "olive-oil"],
    sku: "PAL-OLV-178",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Palmer's Olive Oil Formula Shampoo",
    titleAr: "بالمرز شامبو زيت الزيتون",
    description: "Smoothing shampoo with extra virgin olive oil that cleanses while adding moisture and shine.",
    descriptionAr: "شامبو ملطف بزيت الزيتون البكر الممتاز ينظف مع إضافة الرطوبة واللمعان.",
    category: "Hair Care",
    subcategory: "shampoo",
    brand: "Palmer's",
    price: 9.75,
    isOnSale: false,
    volumeMl: "400ml",
    skinConcerns: [],
    tags: ["smoothing", "olive-oil"],
    sku: "PAL-SHA-400",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Palmer's Olive Oil Formula Conditioner",
    titleAr: "بالمرز بلسم زيت الزيتون",
    description: "Replenishing conditioner that restores shine and manageability to dry, damaged hair.",
    descriptionAr: "بلسم معوض يستعيد اللمعان والتحكم للشعر الجاف والتالف.",
    category: "Hair Care",
    subcategory: "conditioner",
    brand: "Palmer's",
    price: 9.75,
    isOnSale: false,
    volumeMl: "400ml",
    skinConcerns: [],
    tags: ["conditioning", "olive-oil"],
    sku: "PAL-CON-400",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Palmer's Cocoa Butter Formula Hair Silk",
    titleAr: "بالمرز سيلك الشعر بزبدة الكاكاو",
    description: "Hair treatment with cocoa butter and vitamin E that repairs and protects damaged hair.",
    descriptionAr: "علاج للشعر بزبدة الكاكاو وفيتامين E يصلح ويحمي الشعر التالف.",
    category: "Hair Care",
    subcategory: "treatments",
    brand: "Palmer's",
    price: 7.50,
    isOnSale: false,
    volumeMl: "178ml",
    skinConcerns: [],
    tags: ["repair", "cocoa-butter"],
    sku: "PAL-SIL-178",
    inStock: true,
  },

  // Olaplex Products
  {
    id: generateId(),
    title: "Olaplex No.3 Hair Perfector",
    titleAr: "أولابلكس رقم 3 معالج الشعر",
    description: "At-home treatment that reduces breakage and strengthens hair by repairing damaged bonds.",
    descriptionAr: "علاج منزلي يقلل التكسر ويقوي الشعر عن طريق إصلاح الروابط التالفة.",
    category: "Hair Care",
    subcategory: "treatments",
    brand: "Olaplex",
    price: 45.00,
    isOnSale: false,
    volumeMl: "100ml",
    skinConcerns: [],
    tags: ["bond-repair", "bestseller"],
    sku: "OLA-003-100",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Olaplex No.4 Bond Maintenance Shampoo",
    titleAr: "أولابلكس رقم 4 شامبو صيانة الروابط",
    description: "Highly moisturizing shampoo that repairs and protects hair from everyday damage.",
    descriptionAr: "شامبو مرطب للغاية يصلح ويحمي الشعر من التلف اليومي.",
    category: "Hair Care",
    subcategory: "shampoo",
    brand: "Olaplex",
    price: 48.00,
    isOnSale: false,
    volumeMl: "250ml",
    skinConcerns: [],
    tags: ["bond-repair", "moisturizing"],
    sku: "OLA-004-250",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Olaplex No.5 Bond Maintenance Conditioner",
    titleAr: "أولابلكس رقم 5 بلسم صيانة الروابط",
    description: "Highly moisturizing conditioner that restores, repairs, and hydrates without adding weight.",
    descriptionAr: "بلسم مرطب للغاية يستعيد ويصلح ويرطب دون إضافة ثقل.",
    category: "Hair Care",
    subcategory: "conditioner",
    brand: "Olaplex",
    price: 48.00,
    isOnSale: false,
    volumeMl: "250ml",
    skinConcerns: [],
    tags: ["bond-repair", "hydrating"],
    sku: "OLA-005-250",
    inStock: true,
  },

  // ==================== BODY CARE ====================
  // Palmer's Body Products
  {
    id: generateId(),
    title: "Palmer's Cocoa Butter Formula Body Lotion",
    titleAr: "بالمرز لوشن الجسم بزبدة الكاكاو",
    description: "Rich moisturizing lotion with cocoa butter and vitamin E for dry skin.",
    descriptionAr: "لوشن مرطب غني بزبدة الكاكاو وفيتامين E للبشرة الجافة.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Palmer's",
    price: 14.95,
    isOnSale: false,
    volumeMl: "400ml",
    skinConcerns: ["dry-skin", "hydration"],
    tags: ["cocoa-butter", "moisturizing"],
    sku: "PAL-BOD-400",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Palmer's Cocoa Butter Formula Stretch Marks Cream",
    titleAr: "بالمرز كريم علامات التمدد بزبدة الكاكاو",
    description: "Massage cream that helps improve skin elasticity and reduce appearance of stretch marks.",
    descriptionAr: "كريم تدليك يساعد على تحسين مرونة البشرة وتقليل ظهور علامات التمدد.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Palmer's",
    price: 12.50,
    isOnSale: false,
    volumeMl: "125g",
    skinConcerns: ["hydration"],
    tags: ["stretch-marks", "pregnancy"],
    sku: "PAL-STR-125",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Palmer's Skin Success Fade Cream",
    titleAr: "بالمرز سكين ساكسس كريم توحيد اللون",
    description: "Even tone moisturizer that fades dark spots and evens skin tone.",
    descriptionAr: "مرطب موحد للون يخفف البقع الداكنة ويوحد لون البشرة.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Palmer's",
    price: 15.95,
    isOnSale: false,
    volumeMl: "75g",
    skinConcerns: ["dark-spots"],
    tags: ["brightening", "even-tone"],
    sku: "PAL-FAD-75",
    inStock: true,
  },

  // Jergens Products
  {
    id: generateId(),
    title: "Jergens Ultra Healing Extra Dry Skin Moisturizer",
    titleAr: "جيرجينز مرطب الشفاء للبشرة الجافة جداً",
    description: "Deep moisturizer that heals and restores dry skin with vitamins C, E, and B5.",
    descriptionAr: "مرطب عميق يشفي ويستعيد البشرة الجافة مع فيتامينات C و E و B5.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Jergens",
    price: 10.50,
    isOnSale: false,
    volumeMl: "600ml",
    skinConcerns: ["dry-skin", "hydration"],
    tags: ["ultra-healing", "extra-dry"],
    sku: "JER-ULT-600",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Jergens Natural Glow Daily Moisturizer",
    titleAr: "جيرجينز ناتشورال غلو مرطب يومي",
    description: "Gradual self-tanner that builds a natural-looking tan while moisturizing.",
    descriptionAr: "مسمر تدريجي يبني سمرة طبيعية المظهر مع الترطيب.",
    category: "Body Care",
    subcategory: "body-lotion",
    brand: "Jergens",
    price: 12.00,
    isOnSale: false,
    volumeMl: "221ml",
    skinConcerns: ["hydration"],
    tags: ["self-tanner", "gradual"],
    sku: "JER-GLO-221",
    inStock: true,
  },

  // ==================== MAKEUP ====================
  // Bourjois Products
  {
    id: generateId(),
    title: "Bourjois Healthy Mix Foundation",
    titleAr: "بورجوا هيلثي ميكس فاونديشن",
    description: "Medium coverage foundation that brightens and smoothes for a healthy glow.",
    descriptionAr: "فاونديشن بتغطية متوسطة يفتح وينعم للحصول على توهج صحي.",
    category: "Make Up",
    subcategory: "face-makeup",
    brand: "Bourjois",
    price: 18.00,
    originalPrice: 22.00,
    discountPercent: 18,
    isOnSale: true,
    volumeMl: "30ml",
    skinConcerns: [],
    tags: ["foundation", "healthy-glow"],
    sku: "BOU-HEA-30",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Bourjois Volume Glamour Push Up Mascara",
    titleAr: "بورجوا ماسكارا فوليوم غلامور",
    description: "Volume mascara with push-up effect for dramatic lashes.",
    descriptionAr: "ماسكارا حجم مع تأثير رفع للرموش الدراماتيكية.",
    category: "Make Up",
    subcategory: "eye-makeup",
    brand: "Bourjois",
    price: 15.00,
    isOnSale: false,
    volumeMl: "7ml",
    skinConcerns: [],
    tags: ["mascara", "volume"],
    sku: "BOU-MAS-7",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Bourjois Rouge Velvet The Lipstick",
    titleAr: "بورجوا روج فيلفيت أحمر الشفاه",
    description: "Matte lipstick with velvet texture that lasts up to 24 hours.",
    descriptionAr: "أحمر شفاه مطفي بملمس مخملي يدوم حتى 24 ساعة.",
    category: "Make Up",
    subcategory: "lip-makeup",
    brand: "Bourjois",
    price: 12.00,
    isOnSale: false,
    volumeMl: "2.4g",
    skinConcerns: [],
    tags: ["lipstick", "matte"],
    sku: "BOU-LIP-24",
    inStock: true,
  },

  // Essence Products
  {
    id: generateId(),
    title: "Essence Lash Princess False Lash Effect Mascara",
    titleAr: "إيسنس لاش برنسيس ماسكارا تأثير الرموش الصناعية",
    description: "Volume mascara that creates false lash effect with dramatic length and volume.",
    descriptionAr: "ماسكارا حجم تخلق تأثير الرموش الصناعية مع طول وحجم دراماتيكي.",
    category: "Make Up",
    subcategory: "eye-makeup",
    brand: "Essence",
    price: 6.00,
    isOnSale: false,
    volumeMl: "12ml",
    skinConcerns: [],
    tags: ["mascara", "bestseller"],
    sku: "ESS-LAS-12",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Essence Make Me Brow Eyebrow Gel Mascara",
    titleAr: "إيسنس ميك مي برو جل الحواجب",
    description: "Tinted eyebrow gel that fills in brows and keeps them in place all day.",
    descriptionAr: "جل حواجب ملون يملأ الحواجب ويثبتها طوال اليوم.",
    category: "Make Up",
    subcategory: "eye-makeup",
    brand: "Essence",
    price: 5.50,
    isOnSale: false,
    volumeMl: "3.8ml",
    skinConcerns: [],
    tags: ["brows", "gel"],
    sku: "ESS-BRO-38",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Essence Pure Nude Highlighter",
    titleAr: "إيسنس بيور نود هايلايتر",
    description: "Subtle highlighter that adds a natural luminous glow.",
    descriptionAr: "هايلايتر رقيق يضيف توهجًا طبيعيًا مضيئًا.",
    category: "Make Up",
    subcategory: "face-makeup",
    brand: "Essence",
    price: 6.00,
    isOnSale: false,
    volumeMl: "7g",
    skinConcerns: [],
    tags: ["highlighter", "natural"],
    sku: "ESS-HIG-7",
    inStock: true,
  },

  // IsaDora Products
  {
    id: generateId(),
    title: "IsaDora Build-up Extra Volume Mascara",
    titleAr: "إيزادورا ماسكارا الحجم الإضافي",
    description: "Buildable volume mascara for customizable lash intensity.",
    descriptionAr: "ماسكارا حجم قابلة للبناء لكثافة رموش قابلة للتخصيص.",
    category: "Make Up",
    subcategory: "eye-makeup",
    brand: "IsaDora",
    price: 18.00,
    isOnSale: false,
    volumeMl: "12ml",
    skinConcerns: [],
    tags: ["mascara", "buildable"],
    sku: "ISA-VOL-12",
    inStock: true,
  },
  {
    id: generateId(),
    title: "IsaDora Perfect Moisture Lipstick",
    titleAr: "إيزادورا أحمر شفاه الترطيب المثالي",
    description: "Moisturizing lipstick with brilliant color and comfortable wear.",
    descriptionAr: "أحمر شفاه مرطب بلون رائع وراحة في الارتداء.",
    category: "Make Up",
    subcategory: "lip-makeup",
    brand: "IsaDora",
    price: 14.00,
    isOnSale: false,
    volumeMl: "4.5g",
    skinConcerns: [],
    tags: ["lipstick", "moisturizing"],
    sku: "ISA-LIP-45",
    inStock: true,
  },

  // ==================== FRAGRANCES ====================
  {
    id: generateId(),
    title: "Versace Bright Crystal EDT",
    titleAr: "فيرساتشي برايت كريستال عطر",
    description: "A precious jewel of rare beauty, fresh and sensual floral fragrance.",
    descriptionAr: "جوهرة ثمينة من الجمال النادر، عطر زهري منعش وحسي.",
    category: "Fragrances",
    subcategory: "women",
    brand: "Versace",
    price: 85.00,
    originalPrice: 95.00,
    discountPercent: 11,
    isOnSale: true,
    volumeMl: "90ml",
    skinConcerns: [],
    tags: ["floral", "fresh"],
    sku: "VER-BRI-90",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Calvin Klein Eternity for Women EDP",
    titleAr: "كالفن كلاين إيتيرنيتي للنساء عطر",
    description: "Romantic floral fragrance that captures the spirit of lasting love.",
    descriptionAr: "عطر زهري رومانسي يجسد روح الحب الدائم.",
    category: "Fragrances",
    subcategory: "women",
    brand: "Calvin Klein",
    price: 75.00,
    isOnSale: false,
    volumeMl: "100ml",
    skinConcerns: [],
    tags: ["floral", "romantic"],
    sku: "CK-ETE-100",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Dolce & Gabbana Light Blue EDT",
    titleAr: "دولتشي آند غابانا لايت بلو عطر",
    description: "Fresh fruity floral fragrance inspired by Mediterranean summer.",
    descriptionAr: "عطر فواكه زهري منعش مستوحى من صيف البحر الأبيض المتوسط.",
    category: "Fragrances",
    subcategory: "women",
    brand: "Dolce & Gabbana",
    price: 95.00,
    isOnSale: false,
    volumeMl: "100ml",
    skinConcerns: [],
    tags: ["fresh", "citrus"],
    sku: "DG-LIG-100",
    inStock: true,
  },

  // ==================== TOOLS & DEVICES ====================
  {
    id: generateId(),
    title: "Mavala Double-Lash Nutritive Treatment",
    titleAr: "مافالا دبل لاش علاج مغذي للرموش",
    description: "Strengthening treatment that promotes longer, thicker lashes.",
    descriptionAr: "علاج مقوي يعزز الرموش الأطول والأكثر كثافة.",
    category: "Tools & Devices",
    subcategory: "brushes-tools",
    brand: "Mavala",
    price: 25.00,
    isOnSale: false,
    volumeMl: "10ml",
    skinConcerns: [],
    tags: ["lash-growth", "treatment"],
    sku: "MAV-DOU-10",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Smilest Teeth Whitening Kit",
    titleAr: "سمايلست طقم تبييض الأسنان",
    description: "Professional teeth whitening kit with LED accelerator for visible results.",
    descriptionAr: "طقم تبييض أسنان احترافي مع مسرع LED لنتائج مرئية.",
    category: "Tools & Devices",
    subcategory: "brushes-tools",
    brand: "Smilest",
    price: 35.00,
    originalPrice: 45.00,
    discountPercent: 22,
    isOnSale: true,
    volumeMl: "1 Kit",
    skinConcerns: [],
    tags: ["whitening", "dental"],
    sku: "SMI-WHI-KIT",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Real Techniques Expert Face Brush",
    titleAr: "ريال تكنيكس فرشاة الوجه الخبيرة",
    description: "Multi-purpose brush perfect for applying foundation, BB cream, and primers.",
    descriptionAr: "فرشاة متعددة الاستخدامات مثالية لتطبيق كريم الأساس وكريم بي بي والبرايمر.",
    category: "Tools & Devices",
    subcategory: "brushes-tools",
    brand: "Real Techniques",
    price: 12.00,
    isOnSale: false,
    volumeMl: "1 piece",
    skinConcerns: [],
    tags: ["brush", "face"],
    sku: "RT-EXP-1",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Beautyblender Original Makeup Sponge",
    titleAr: "بيوتي بلندر إسفنجة المكياج الأصلية",
    description: "Revolutionary edgeless sponge for a flawless, airbrushed finish.",
    descriptionAr: "إسفنجة ثورية بدون حواف للحصول على لمسة نهائية خالية من العيوب.",
    category: "Tools & Devices",
    subcategory: "brushes-tools",
    brand: "Beautyblender",
    price: 18.00,
    isOnSale: false,
    volumeMl: "1 piece",
    skinConcerns: [],
    tags: ["sponge", "blending"],
    sku: "BB-ORI-1",
    inStock: true,
  },

  // ==================== HEALTH & SUPPLEMENTS ====================
  {
    id: generateId(),
    title: "Jamieson Vitamin C 500mg Chewable",
    titleAr: "جاميسون فيتامين سي 500 ملغ قابل للمضغ",
    description: "Delicious orange-flavored chewable vitamin C for immune support.",
    descriptionAr: "فيتامين سي قابل للمضغ بنكهة البرتقال اللذيذة لدعم المناعة.",
    category: "Health & Supplements",
    subcategory: "vitamins",
    brand: "Jamieson",
    price: 13.90,
    isOnSale: false,
    volumeMl: "120 Tablets",
    skinConcerns: [],
    tags: ["vitamin-c", "immune"],
    sku: "JAM-VIC-120",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Sundown Papaya Enzyme Chewable",
    titleAr: "صن داون إنزيم البابايا قابل للمضغ",
    description: "Natural digestive enzyme supplement for healthy digestion.",
    descriptionAr: "مكمل إنزيم هضمي طبيعي لصحة الجهاز الهضمي.",
    category: "Health & Supplements",
    subcategory: "supplements",
    brand: "Sundown",
    price: 12.90,
    isOnSale: false,
    volumeMl: "100 Tablets",
    skinConcerns: [],
    tags: ["digestive", "enzyme"],
    sku: "SUN-PAP-100",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Jamieson Omega-3 Complete",
    titleAr: "جاميسون أوميغا-3 كامل",
    description: "High-quality fish oil supplement for heart, brain, and joint health.",
    descriptionAr: "مكمل زيت السمك عالي الجودة لصحة القلب والدماغ والمفاصل.",
    category: "Health & Supplements",
    subcategory: "supplements",
    brand: "Jamieson",
    price: 18.50,
    isOnSale: false,
    volumeMl: "80 Softgels",
    skinConcerns: [],
    tags: ["omega-3", "heart-health"],
    sku: "JAM-OME-80",
    inStock: true,
  },

  // ==================== DEODORANTS ====================
  {
    id: generateId(),
    title: "Speed Stick Ocean Surf Deodorant",
    titleAr: "سبيد ستيك أوشن سيرف مزيل العرق",
    description: "24-hour protection deodorant with fresh ocean scent.",
    descriptionAr: "مزيل عرق بحماية 24 ساعة مع رائحة المحيط المنعشة.",
    category: "Body Care",
    subcategory: "deodorant",
    brand: "Speed Stick",
    price: 2.75,
    isOnSale: false,
    volumeMl: "51g",
    skinConcerns: [],
    tags: ["deodorant", "fresh"],
    sku: "SPE-OCE-51",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Old Spice Original Deodorant Stick",
    titleAr: "أولد سبايس مزيل العرق الأصلي",
    description: "Classic masculine deodorant with long-lasting protection.",
    descriptionAr: "مزيل عرق رجالي كلاسيكي مع حماية طويلة الأمد.",
    category: "Body Care",
    subcategory: "deodorant",
    brand: "Old Spice",
    price: 5.50,
    isOnSale: false,
    volumeMl: "50ml",
    skinConcerns: [],
    tags: ["deodorant", "men"],
    sku: "OLD-ORI-50",
    inStock: true,
  },
  {
    id: generateId(),
    title: "Secret Powder Fresh Invisible Solid",
    titleAr: "سيكريت بودر فريش مزيل العرق الصلب",
    description: "Invisible solid deodorant with powder fresh scent for women.",
    descriptionAr: "مزيل عرق صلب غير مرئي برائحة البودرة المنعشة للنساء.",
    category: "Body Care",
    subcategory: "deodorant",
    brand: "Secret",
    price: 6.00,
    isOnSale: false,
    volumeMl: "73g",
    skinConcerns: [],
    tags: ["deodorant", "women"],
    sku: "SEC-POW-73",
    inStock: true,
  },
];

// Get products by category
export function getProductsByCategory(category: string): ProductData[] {
  return PRODUCT_CATALOG.filter(p => p.category === category);
}

// Get products by brand
export function getProductsByBrand(brand: string): ProductData[] {
  return PRODUCT_CATALOG.filter(p => p.brand.toLowerCase() === brand.toLowerCase());
}

// Get products on sale
export function getSaleProducts(): ProductData[] {
  return PRODUCT_CATALOG.filter(p => p.isOnSale);
}

// Get bestsellers (products with bestseller tag)
export function getBestSellers(): ProductData[] {
  return PRODUCT_CATALOG.filter(p => p.tags.includes('bestseller'));
}

// Search products
export function searchProducts(query: string): ProductData[] {
  const lowerQuery = query.toLowerCase();
  return PRODUCT_CATALOG.filter(p => 
    p.title.toLowerCase().includes(lowerQuery) ||
    p.titleAr.includes(query) ||
    p.brand.toLowerCase().includes(lowerQuery) ||
    p.category.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery))
  );
}

// Get featured products (first 8 products, mix of categories)
export function getFeaturedProducts(): ProductData[] {
  const categories = ['Skin Care', 'Hair Care', 'Make Up', 'Body Care'];
  const featured: ProductData[] = [];
  
  for (const category of categories) {
    const categoryProducts = getProductsByCategory(category);
    featured.push(...categoryProducts.slice(0, 2));
  }
  
  return featured;
}

// Get all unique brands
export function getAllBrands(): string[] {
  const brands = new Set(PRODUCT_CATALOG.map(p => p.brand));
  return Array.from(brands).sort();
}

// Get all categories
export function getAllCategories(): string[] {
  const categories = new Set(PRODUCT_CATALOG.map(p => p.category));
  return Array.from(categories);
}

// Export total count
export const TOTAL_PRODUCTS = PRODUCT_CATALOG.length;
