
import ExcelJS from "exceljs";
import fs from "fs";
import path from "path";

// Category mapping based on product keywords (copied from edge function)
const CATEGORY_KEYWORDS = {
  "Skin Care": [
    "cream", "lotion", "serum", "moisturizer", "cleanser", "toner", "mask", "scrub",
    "sunscreen", "spf", "anti-aging", "wrinkle", "acne", "facial", "face", "skin",
    "كريم", "مرطب", "واقي", "بشرة", "وجه"
  ],
  "Hair Care": [
    "shampoo", "conditioner", "hair", "oil", "treatment", "mask", "spray",
    "شعر", "شامبو", "بلسم", "زيت"
  ],
  "Body Care": [
    "body lotion", "body wash", "soap", "hand cream", "foot", "deodorant",
    "جسم", "صابون", "يد"
  ],
  "Make Up": [
    "mascara", "lipstick", "foundation", "blush", "eyeshadow", "liner", "makeup",
    "nail", "polish", "cosmetic",
    "مكياج", "أحمر", "ماسكارا"
  ],
  "Fragrances": [
    "perfume", "cologne", "fragrance", "eau de", "spray", "scent",
    "عطر", "كولونيا"
  ],
  "Health & Supplements": [
    "vitamin", "supplement", "capsule", "tablet", "mineral", "omega", "probiotic",
    "فيتامين", "كبسولة", "مكمل"
  ],
  "Medical Supplies": [
    "cannula", "syringe", "glove", "bandage", "gauze", "medical", "surgical",
    "oximeter", "crutch",
    "طبي", "عكاز"
  ],
  "Personal Care": [
    "toothbrush", "toothpaste", "brush", "comb", "razor", "cotton",
    "فرشاة", "مشط"
  ]
};

function categorizeProduct(productName: string): string {
  const nameLower = productName.toLowerCase();
  
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    for (const keyword of keywords) {
      if (nameLower.includes(keyword.toLowerCase())) {
        return category;
      }
    }
  }
  
  return "Uncategorized";
}

function extractBrand(productName: string): string {
  const knownBrands = [
    "Palmer's", "Palmers", "Eucerin", "Vichy", "Bioderma", "Cetaphil",
    "Jergens", "Old Spice", "Speed Stick", "Sundown", "Jamieson",
    "Arm & Hammer", "Secret", "Teen Spirit", "SVR", "Bourjois",
    "Mavala", "Isadora", "Essence", "Bioten", "Olaplex"
  ];
  
  const nameLower = productName.toLowerCase();
  
  for (const brand of knownBrands) {
    if (nameLower.includes(brand.toLowerCase())) {
      return brand.replace("'s", "'s").replace("Palmers", "Palmer's");
    }
  }
  
  const firstWord = productName.split(/[\s-]/)[0];
  if (firstWord.length > 2 && /^[A-Z]/.test(firstWord)) {
    return firstWord;
  }
  
  return "Generic";
}

// Column name mappings (copied from BulkUpload.tsx)
const COLUMN_MAPPINGS = {
  sku: ["الرمز", "رمز", "SKU", "Code", "Barcode", "الباركود"],
  name: ["اسم المادة", "اسم المنتج", "Product Name", "Name", "المنتج", "الاسم"],
  costPrice: ["الكلفة", "سعر الشراء", "Cost", "Cost Price", "التكلفة"],
  sellingPrice: ["سعر البيع", "السعر", "Price", "Selling Price", "Sale Price"],
};

async function generateMigration() {
  const filePath = path.join(process.cwd(), "كشف المواد  (المواد 16% المتوفرة) عدد 1526 اول كشف.xlsx");
  
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    return;
  }

  console.log(`Reading file: ${filePath}`);
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(filePath);
  
  const worksheet = workbook.worksheets[0];
  if (!worksheet) {
    console.error("No worksheet found");
    return;
  }

  const headerRow = worksheet.getRow(1);
  const headers: string[] = [];
  headerRow.eachCell({ includeEmpty: false }, (cell, colNumber) => {
    headers[colNumber - 1] = String(cell.value || "").trim();
  });

  console.log("Headers:", headers);

  const skuColIdx = headers.findIndex(h => COLUMN_MAPPINGS.sku.some(m => 
    h.toLowerCase().trim() === m.toLowerCase().trim() || h.includes(m) || m.includes(h)
  ));
  const nameColIdx = headers.findIndex(h => COLUMN_MAPPINGS.name.some(m => 
    h.toLowerCase().trim() === m.toLowerCase().trim() || h.includes(m) || m.includes(h)
  ));
  const priceColIdx = headers.findIndex(h => COLUMN_MAPPINGS.sellingPrice.some(m => 
    h.toLowerCase().trim() === m.toLowerCase().trim() || h.includes(m) || m.includes(h)
  ));

  if (nameColIdx === -1 || priceColIdx === -1) {
    console.error("Could not find required columns");
    return;
  }

  let sql = `-- Seed products from Excel file
-- Generated by script

INSERT INTO public.products (title, price, category, brand, description, created_at, updated_at)
VALUES
`;

  const values: string[] = [];
  let count = 0;

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return; // Skip header

    const getCellValue = (colIdx: number): string => {
      if (colIdx === -1) return "";
      const cell = row.getCell(colIdx + 1);
      return String(cell.value || "").trim();
    };

    const name = getCellValue(nameColIdx);
    if (!name) return;

    const priceStr = getCellValue(priceColIdx).replace(/[^0-9.]/g, "");
    const price = parseFloat(priceStr) || 0;
    
    const category = categorizeProduct(name);
    const brand = extractBrand(name);
    
    // Escape single quotes for SQL
    const escape = (str: string) => str.replace(/'/g, "''");
    
    values.push(`('${escape(name)}', ${price}, '${escape(category)}', '${escape(brand)}', 'Imported from bulk upload', NOW(), NOW())`);
    count++;
  });

  if (values.length === 0) {
    console.log("No products found to insert");
    return;
  }

  sql += values.join(",\n") + ";\n";

  const migrationFilename = `20260122000000_seed_products_${Date.now()}.sql`;
  const migrationPath = path.join(process.cwd(), "supabase", "migrations", migrationFilename);
  
  fs.writeFileSync(migrationPath, sql);
  console.log(`Generated migration file: ${migrationPath}`);
  console.log(`Contains ${count} products`);
}

generateMigration().catch(console.error);
